baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'PaperMod'

[menu]
  [[menu.main]]
    identifier = "blogs"
    name = "Blogs"
    url = "/posts/"
    weight = 10
